<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1

|    Term    |                                                                    Brief Description                                                                    |   |   |   |
|:----------:|:-------------------------------------------------------------------------------------------------------------------------------------------------------:|---|---|---|
| Subsetting | Extraction of elements from a larger list of them based on certain parameters or index                                                                  |   |   |   |
|  Indexing  | Python is a 0-index language so the 1st element in a list will be indexed as 0. *Selection of a single element by referencing its position in the list* |   |   |   |
|   Slicing  | *Selecting a range of elements from a list based on a start, end position and interval of selection*                                                    |   |   |   |
|   Masking  | Converting a list into True or False based on a binary condition applied to a whole list.                                                               |   |   |   |

In [1]:
import numpy as np

## Exercise 2

In [2]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [3]:
np_array_int=np.array(np_array_2d[0:,0]).astype(int)
np_array_int

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [4]:
odd_mask = np_array_int % 2 != 0
odd_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [5]:
odd_np_array_elem=np_array_2d[odd_mask,1]
odd_np_array_elem

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

## Exercise 3

### Solution 1

In [21]:
np_array=np.array(
[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

dict={'<':-1, '>':1, '==':0}
for i in dict:
    np_array[eval(f'np_array {i} 50') == 1] = dict[i] # removed unnecessary np.where()
    
print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


### Solution 2

In [7]:
np_array=np.array(
[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

np_array[np.where((np_array < 50) == 1)] = -1
np_array[np.where((np_array > 50) == 1)] = 1
np_array[np.where((np_array == 50) == 1)] = 0 # faster code but less flexible for expansion (?)

print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
