<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [5]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",  # the more intuitive choice in general situation
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [10]:
py_super_names[0]

'Black Widow'

In [11]:
np_super_names[1]

np.str_('Iron Man')

In [14]:
np_real_names[2]='Dr. Chammika'
print(np_real_names)

['Natasha Romanoff' 'Tony Stark' 'Dr. Chammika']


In [17]:
np_real_names[-1] # 1st from the back, useful for long lists + dont know #elemnts

np.str_('Dr. Chammika')

## 1.3 Accessing data from a dictionary

In [20]:
superhero_info['Peter Parker']='Spiderman'
print(superhero_info)

{'Natasha Romanoff': 'Black Widow', 'Tony Stark': 'Iron Man', 'Stephen Strange': 'Doctor Strange', 'Peter Parker': 'Spiderman'}


In [21]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange', 'Peter Parker'])

In [23]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange', 'Spiderman'])

## 1.4 Higher dimensional lists

In [26]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
print(py_superhero_info) #list of lists

[['Natasha Romanoff', 'Black Widow'], ['Tony Stark', 'Iron Man'], ['Stephen Strange', 'Doctor Strange']]


# 2 Lists vs. Arrays

In [28]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [29]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [31]:
np_array_2d # indicates array, data type 

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

## 2.1 Size

In [35]:
len(py_list_2d) # only #1st D elements

10

In [39]:
np_array_2d.shape # no () as not function, is attribute of the array

(10, 2)

In [44]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J","$"]]

In [46]:
print(py_list_2d) # no issue

[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'], [9, 'I'], [10, 'J', '$']]


In [43]:
np_array_2d = np.array(py_list_2d)      # numpy error as dimensions of elements not equal

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.

## 2.2 Arrays are fussy about type

In [47]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [52]:
py_list # 1st stored as integer, 2nd as float, 3rd as string

[1, 1.5, 'A']

In [54]:
np_array # alllll stored as string, U32

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [58]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [60]:
py_list+10

TypeError: can only concatenate list (not "int") to list

In [62]:
np_array+10

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [76]:
[1,2]+[3]

[1, 2, 3]

In [74]:
py_list1 = [1, 2, 3, 4, 5]
np_array1 = np.array(py_list1)  

py_list2 = [6, 7, 8, 9, 10]
np_array2 = np.array(py_list2)  

In [67]:
py_list1+py_list2 #appends lists together

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [68]:
np_array1+np_array2 # elements wise operations

array([ 7,  9, 11, 13, 15])

## 2.5 Multiplying by a Number

In [70]:
py_list*10 # repeats and appends list 10 times

[1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5]

In [71]:
np_array*10

array([10, 20, 30, 40, 50])

## 2.6 Squaring

In [72]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [73]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [79]:
py_list == 3     # Shouldnt have given an answer

False

In [80]:
np_array == 3  

array([False, False,  True, False, False])

In [81]:
np_array > 3  

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [83]:
sum(py_list)     # sum() is a base Python function

15

In [84]:
max(py_list)     # max() is a base Python function

5

In [85]:
min(py_list)     # min() is a base Python function

1

In [86]:
np_array.sum()

np.int64(15)

In [87]:
np_array.max()

np.int64(5)

In [88]:
np_array.min()

np.int64(1)

In [89]:
np_array.mean()

np.float64(3.0)

In [90]:
np_array.std()

np.float64(1.4142135623730951)

In [94]:
print(sum(py_list) , 
max(py_list) , 
min(py_list) , 
np_array.sum(),
np_array.max(),
np_array.min(),
np_array.mean(),
np_array.std()
     )

15 5 1 15 5 1 3.0 1.4142135623730951


In [114]:
np_arrayA=[1,2,3,4,5]

In [104]:
%timeit sum(np_array)

1.87 μs ± 77.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [106]:
%timeit np_array.sum()

4.51 μs ± 217 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [125]:
np_array=np.array([[1,1],[2,1],[3,1],[4,1],[5,1]])
print(
    np_array.sum(),
    np_array.sum(0), # add alls rows tgt
    np_array.sum(1) # add col tgt
)

20 [15  5] [2 3 4 5 6]


|||
|-|-|
|1|1|
|2|1|
|3|1|
|4|1|
|5|1|

## Footnotes