<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

In [3]:
import numpy as np

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [23]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array # works either way

In [17]:
x[0]

np.str_('a1')

In [18]:
x[2:5]

array(['c3', 'd4', 'e5'], dtype='<U3')

In [19]:
x[2:]

array(['c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [20]:
x[2::2] # leave blank for 2nd argument as you want for everything past index 2

array(['c3', 'e5', 'g7', 'i9'], dtype='<U3')

In [21]:
x[2:8:2] # start from index 2, every 2 for the 6 elements

array(['c3', 'e5', 'g7'], dtype='<U3')

In [22]:
x[::-1] # reverses list

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

## 1.2 Arrays only | Subsetting by masking

In [7]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [30]:
np_array > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [27]:
my_mask2 = (np_array > 2) & (np_array < 8)
my_mask2

array([False, False,  True,  True,  True,  True,  True, False, False,
       False])

In [9]:
my_mask2 = (np_array > 8) | (np_array < 5)
my_mask2

array([ True,  True,  True,  True, False, False, False, False,  True,
        True])

In [32]:
np_array[my_mask2] # does not alter the value of np_array

array([3, 4, 5, 6, 7])

In [38]:
my_mask2.sum() # FALSE=0, TRUE=1, counting number of elements that match the mask

np.int64(5)

In [35]:
np_array[~my_mask2] # NOT

array([ 1,  2,  8,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [40]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],         # lists and arrays start to diverge
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [45]:
py_list_2d[3]

[4, 'D']

In [46]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [49]:
py_list_2d[3,1] # thinking like a coordinate system

TypeError: list indices must be integers or slices, not tuple

In [51]:
py_list_2d[3][1] # py_list_2d[3] spits out [4,'D'] then apply [1] to get the index 1 from it

'D'

In [50]:
np_array_2d[3,1] #yayyy

np.str_('D')

In [55]:
x=[[[1,2],[2,3]],[[2,2],[2,3]],[[3,2],[2,3]]] #3D array as each element needs 3 numbers to describe

In [87]:
print(
    f'{x[0]}\n',     # pick index 0 element in 1st dim
    f'{x[0][1]}\n',  # pick index 1 elenment in 2nd dim
    x[0][1][1]       # pick index 1 element in 3rd dim
)

[[1, 2], [2, 3]]
 [2, 3]
 3


## 1.4 Growing lists

In [17]:
x=[1,2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [18]:
x.insert(0,0)

In [19]:
x

[0, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

# Some loose ends

## 1.5 Tuples

In [23]:
x=(1,2,3)
print(x[1])
x[0]=0 #immutable

2


TypeError: 'tuple' object does not support item assignment

In [25]:
x=[1,2,3]
print(x[1])
x[0]=0 #immutable
x

2


[0, 2, 3]

## 1.6 Be VERY careful when copying

## Footnotes